import type { CityEventDefinition } from './types';

/**
 * Every city event, declared rather than branched.
 *
 * `canTrigger` is the hard gate and `weight` shapes how often something shows up
 * once it is allowed. Disasters need an unstable or critical city, celebrations
 * need a healthy one, and the software flavoured events key off engineering
 * signals rather than the health number alone.
 */
export const CITY_EVENT_DEFINITIONS: readonly CityEventDefinition[] = [
  {
    id: 'bug-invasion',
    name: 'Bug Invasion',
    blurb: 'Test failures have attracted unwanted visitors.',
    severity: 'moderate',
    durationMs: 26_000,
    cooldownMs: 70_000,
    canTrigger: (ctx) => ctx.recentFailures >= 1 || ctx.successRate < 0.7,
    weight: (ctx) => 6 + ctx.recentFailures * 5 + (ctx.successRate < 0.6 ? 6 : 0),
  },
  {
    id: 'pr-protest',
    name: 'Pull Request Protest',
    blurb: 'The review queue has organised itself.',
    severity: 'moderate',
    durationMs: 30_000,
    cooldownMs: 90_000,
    canTrigger: (ctx) => ctx.oldPrs >= 3 || ctx.averagePrAgeHours > 30,
    weight: (ctx) => 5 + ctx.oldPrs * 3 + (ctx.waitingPrs > 6 ? 5 : 0),
  },
  {
    id: 'factory-fire',
    name: 'Factory Fire',
    blurb: 'A build pipeline went up in smoke. Literally.',
    severity: 'major',
    durationMs: 24_000,
    cooldownMs: 120_000,
    canTrigger: (ctx) => ctx.failureStreak >= 2 || (ctx.band !== 'thriving' && ctx.recentFailures >= 2),
    weight: (ctx) => 4 + ctx.failureStreak * 4,
  },
  {
    id: 'blackout',
    name: 'City Blackout',
    blurb: 'Infrastructure health could be better.',
    severity: 'major',
    durationMs: 20_000,
    cooldownMs: 150_000,
    canTrigger: (ctx) => ctx.band === 'critical' || (ctx.band === 'unstable' && ctx.recentFailures >= 3),
    weight: (ctx) => (ctx.band === 'critical' ? 10 : 4),
  },
  {
    id: 'traffic-jam',
    name: 'Traffic Jam',
    blurb: 'Queued builds, queued cars.',
    severity: 'moderate',
    durationMs: 24_000,
    cooldownMs: 80_000,
    canTrigger: (ctx) => ctx.band === 'unstable' || ctx.band === 'critical' || ctx.runningRuns >= 4,
    weight: (ctx) => 6 + (ctx.runningRuns >= 4 ? 5 : 0),
  },
  {
    id: 'tornado',
    name: 'Tornado Warning',
    blurb: 'Critical engineering health has consequences.',
    severity: 'chaotic',
    durationMs: 22_000,
    cooldownMs: 300_000,
    canTrigger: (ctx) => ctx.band === 'critical' && ctx.recentFailures >= 2,
    weight: () => 3,
  },
  {
    id: 'ufo',
    name: 'UFO Sighting',
    blurb: 'Apparently code review is not the biggest problem today.',
    severity: 'chaotic',
    durationMs: 24_000,
    cooldownMs: 300_000,
    canTrigger: (ctx) => ctx.band === 'critical' || (ctx.oldPrs >= 4 && ctx.band !== 'thriving'),
    weight: (ctx) => 3 + (ctx.oldPrs >= 5 ? 2 : 0),
  },
  {
    id: 'meteor',
    name: 'Meteor Strike',
    blurb: 'Someone force pushed to main.',
    severity: 'chaotic',
    durationMs: 20_000,
    cooldownMs: 360_000,
    canTrigger: (ctx) => ctx.band === 'critical' && ctx.failureStreak >= 3,
    weight: () => 2,
  },
  {
    id: 'deployment-parade',
    name: 'Deployment Parade',
    blurb: 'Shipping streak. The city noticed.',
    severity: 'moderate',
    durationMs: 30_000,
    cooldownMs: 110_000,
    canTrigger: (ctx) => ctx.recentDeploys >= 3 && (ctx.band === 'healthy' || ctx.band === 'thriving'),
    weight: (ctx) => 5 + ctx.recentDeploys * 2,
  },
  {
    id: 'fireworks',
    name: 'Fireworks',
    blurb: 'Green builds all round.',
    severity: 'minor',
    durationMs: 14_000,
    cooldownMs: 70_000,
    canTrigger: (ctx) => ctx.band === 'thriving' || ctx.recentDeploys >= 4,
    weight: (ctx) => 6 + (ctx.health >= 95 ? 4 : 0),
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    blurb: 'The city recovered. Everyone feels better.',
    severity: 'minor',
    durationMs: 18_000,
    cooldownMs: 90_000,
    canTrigger: (ctx) => ctx.healthDelta >= 15 && ctx.band !== 'critical',
    weight: (ctx) => 5 + Math.round(ctx.healthDelta / 5),
  },
  {
    id: 'repair-crew',
    name: 'Repair Crews',
    blurb: 'Maintenance is restoring the district.',
    severity: 'minor',
    durationMs: 20_000,
    cooldownMs: 60_000,
    canTrigger: (ctx) => ctx.healthDelta >= 8 || (ctx.band === 'unstable' && ctx.recentFailures <= 1),
    weight: () => 5,
  },
  {
    id: 'construction-boom',
    name: 'Construction Boom',
    blurb: 'Sustained green pipelines pay for new buildings.',
    severity: 'minor',
    durationMs: 28_000,
    cooldownMs: 120_000,
    canTrigger: (ctx) => ctx.band === 'thriving' && ctx.successRate >= 0.8,
    weight: () => 4,
  },
];
